### ISSUE TITLE
2.1.2 - NoMethodError - undefined method `private_id'

### ISSUE THREAD

**Issue by worldlywisdom** [redis-store/redis-rack#55]
I'm getting an NoMethodError - undefined method `private_id' in version 2.1.2. My application is working with version 2.0.6 - no other changes.

This matches the error referenced by @Looooong in https://github.com/redis-store/redis-rack/pull/50#issuecomment-582828057

Gems:
* rack (2.2.2)
* sinatra (2.0.8.1)
* redis (4.1.3)
* redis-rack (2.1.2)
* redis-store (1.8.2)
* hiredis (0.6.3)

Backtrace:

/ruby/2.6.5/gems/redis-rack-2.1.2/lib/rack/session/redis.rb in block (2 levels) in write_session
          with { |c| c.set sid.private_id, new_session, options }
/ruby/2.6.5/gems/redis-rack-2.1.2/lib/redis/rack/connection.rb in with
          block.call(store)
/ruby/2.6.5/gems/redis-rack-2.1.2/lib/rack/session/redis.rb in with
        @conn.with(&block)
/ruby/2.6.5/gems/redis-rack-2.1.2/lib/rack/session/redis.rb in block in write_session
          with { |c| c.set sid.private_id, new_session, options }
/ruby/2.6.5/gems/redis-rack-2.1.2/lib/rack/session/redis.rb in with_lock
        yield
/ruby/2.6.5/gems/redis-rack-2.1.2/lib/rack/session/redis.rb in write_session
        with_lock(req, false) do
/ruby/2.6.5/gems/rack-2.2.2/lib/rack/session/abstract/id.rb in commit_session
          if not data = write_session(req, session_id, session_data, options)
/ruby/2.6.5/gems/rack-2.2.2/lib/rack/session/abstract/id.rb in context
          commit_session(req, res)
/ruby/2.6.5/gems/rack-2.2.2/lib/rack/session/abstract/id.rb in call
          context(env)
/ruby/2.6.5/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb in call
        status, headers, body = @app.call(env)
/ruby/2.6.5/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb in call
        app.call env
/ruby/2.6.5/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb in call
        status, headers, body = app.call(env)
/ruby/2.6.5/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb in call
        result or app.call(env)
/ruby/2.6.5/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb in call
        result or app.call(env)
/ruby/2.6.5/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb in call
        status, headers, body        = @app.call(env)
/ruby/2.6.5/gems/rack-2.2.2/lib/rack/logger.rb in call
      @app.call(env)
/ruby/2.6.5/gems/rack-2.2.2/lib/rack/common_logger.rb in call
      status, headers, body = @app.call(env)
/ruby/2.6.5/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in call
        call_without_check(env)
/ruby/2.6.5/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in call
      env['sinatra.commonlogger'] ? @app.call(env) : super
/ruby/2.6.5/gems/rack-2.2.2/lib/rack/head.rb in call
      status, headers, body = @app.call(env)
/ruby/2.6.5/gems/rack-2.2.2/lib/rack/method_override.rb in call
      @app.call(env)
/ruby/2.6.5/gems/sinatra-2.0.8.1/lib/sinatra/show_exceptions.rb in call
      @app.call(env)
/ruby/2.6.5/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in call
      result, callback = app.call(env), env['async.callback']
/ruby/2.6.5/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in call
      @stack.call(env)
/ruby/2.6.5/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in block in call
        synchronize { prototype.call(env) }
/ruby/2.6.5/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in synchronize
          yield
/ruby/2.6.5/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in call
        synchronize { prototype.call(env) }
/ruby/2.6.5/gems/puma-4.3.3/lib/puma/configuration.rb in call
        @app.call(env)
/ruby/2.6.5/gems/puma-4.3.3/lib/puma/server.rb in handle_request
          status, headers, res_body = @app.call(env)
/ruby/2.6.5/gems/puma-4.3.3/lib/puma/server.rb in process_client
          case handle_request(client, buffer)
/ruby/2.6.5/gems/puma-4.3.3/lib/puma/server.rb in block in run
            process_client client, buffer
/ruby/2.6.5/gems/puma-4.3.3/lib/puma/thread_pool.rb in block in spawn_thread
            block.call(work, *extra)

**Comment by Looooong** [comment]
I think that the gem parses the session ID, which was stored in cookies, was generated before rack 2.0.8. That session ID is incompatible with the newer rack version, hence this error. I cleared the cookies and this error disappeared.

**Comment by worldlywisdom** [comment]
That fixed the issue. Thanks for your help!
